apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-set
  namespace: arc-runners
spec:
  interval: 1h
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-mainline
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: arc-operator
      namespace: arc-systems
  values:
    githubConfigUrl: "https://github.com/kg6zjl/clusters"
    githubConfigSecret: github-runner-secret
    minReplicas: 3
    maxReplicas: 10
    controllerServiceAccount:
      name: arc-operator-gha-runner-scale-set-controller
      namespace: arc-systems
    template:
      spec:
        containers:
          - name: runner
            image: registry.kube.stevearnett.com/github-runner-optimized:latest
            command: ["/home/runner/run.sh"]
