apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: registry-secrets
  data:
    - secretKey: htpasswd
      remoteRef:
        key: registry-htpasswd
        property: password
    - secretKey: REGISTRY_PASSWORD
      remoteRef:
        key: registry-htpasswd
        property: docker-password
