apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zot
  namespace: registry
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zot
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
