apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: reflector

spec:
  releaseName: reflector
  chart:
    spec:
      chart: emberstack/reflector
      version: v9.0.322
      repo: https://emberstack.github.io/helm-charts
