apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pigallery2-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: pigallery2-secret
  data:
    - secretKey: Server-sessionSecret
      remoteRef:
        key: pigallery2-session-secret
        property: password
