apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-services-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: ai-services-secrets
  data:
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: webui-secret-key
        property: password
