apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: monitoring-secrets
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-password
        property: username
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: grafana-admin-password
        property: password
