resources:
  - network-policy.yaml
  - namespace.yaml
  - ingressroute-grafana.yaml
  - ingressroute-prometheus.yaml
  - ingressroute-alertmanager.yaml
  - prometheus-rules.yaml
  - dashboard-ugreen-nas.yaml
  - external-secrets.yaml
  - kube-prometheus-stack-helmrelease.yaml
  - loki-helmrelease.yaml
  - promtail-helmrelease.yaml
  - blackbox-exporter-helmrelease.yaml

configMapGenerator:

generatorOptions:
  disableNameSuffixHash: true
