apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - plexinc-helmrepository.yaml
  - helmrelease.yaml
  - network-policy.yaml
  - namespace.yaml
  - dnsendpoint.yaml
  - ingress.yaml
  - external-secrets.yaml

generatorOptions:
  disableNameSuffixHash: true
