apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openclaw
  namespace: openclaw
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`claw.kube.stevearnett.com`)
      kind: Rule
      services:
        - name: openclaw
          port: 18789
          scheme: http
          serversTransport: openclaw-http11
  tls:
    secretName: wildcard-stevearnett-com-tls
