apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openclaw-allow-external
  namespace: openclaw
spec:
  podSelector: 
  ingress:
  - ports:
    - port: 18789
      protocol: TCP
  policyTypes:
  - Ingress
