apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clustersecret-allow-egress
  namespace: clustersecret
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
    - protocol: TCP
      port: 443
    to:
    - namespaceSelector: {}
  ingress:
  - from:
    - namespaceSelector: {}
