apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-secrets-allow-egress
  namespace: external-secrets
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
    - protocol: TCP
      port: 443
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    ports:
    - protocol: TCP
      port: 443
  - to:
    - ipBlock:
        cidr: 10.152.183.1/32
    ports:
    - protocol: TCP
      port: 443
  - to:
    - namespaceSelector: {}
  ingress:
  - from:
    - namespaceSelector: {}
