---
- name: "Resolve secret: {{ item.key }}"
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ lookup('community.general.onepassword', item.value, errors='warn') }}"
  loop: "{{ op_secrets | dict2items }}"
  when:
    - item.value | length > 0
    - lookup('env', 'SKIP_OP') | default('0') | int == 0
  no_log: true