apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - network-policy.yaml
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - pvc.yaml
  - nodered-data-longhorn-pvc.yaml
  - nodered-migration.yaml
  - dnsendpoint.yaml