apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: plane
spec:
  endpoints:
    - dnsName: kanban.kube.stevearnett.com
      recordTTL: 300
      recordType: A
      targets:
        - "192.168.1.241"
