apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-app-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: plane-app-env
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secret_key }}"
        LIVE_SERVER_SECRET_KEY: "{{ .live_key }}"
        REDIS_URL: "redis://plane-redis.plane.svc.cluster.local:6379/"
        DATABASE_URL: "postgresql://plane:{{ .pg_pass }}@plane-pgdb.plane.svc.cluster.local/plane"
        AMQP_URL: "amqp://plane:{{ .mq_pass }}@plane-rabbitmq.plane.svc.cluster.local/"
  data:
    - secretKey: secret_key
      remoteRef:
        key: plane-secret-key
        property: password
    - secretKey: live_key
      remoteRef:
        key: plane-live-secret-key
        property: password
    - secretKey: pg_pass
      remoteRef:
        key: plane-pg-password
        property: password
    - secretKey: mq_pass
      remoteRef:
        key: plane-mq-password
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-live-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: plane-live-env
    template:
      engineVersion: v2
      data:
        LIVE_SERVER_SECRET_KEY: "{{ .live_key }}"
        REDIS_URL: "redis://plane-redis.plane.svc.cluster.local:6379/"
  data:
    - secretKey: live_key
      remoteRef:
        key: plane-live-secret-key
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-pgdb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: plane-pgdb
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: plane
        POSTGRES_DB: plane
        POSTGRES_PASSWORD: "{{ .pg_pass }}"
  data:
    - secretKey: pg_pass
      remoteRef:
        key: plane-pg-password
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-rabbitmq
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: plane-rabbitmq
    template:
      engineVersion: v2
      data:
        RABBITMQ_DEFAULT_USER: plane
        RABBITMQ_DEFAULT_PASS: "{{ .mq_pass }}"
  data:
    - secretKey: mq_pass
      remoteRef:
        key: plane-mq-password
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-doc-store
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: plane-doc-store
    template:
      engineVersion: v2
      data:
        FILE_SIZE_LIMIT: "5242880"
        AWS_S3_BUCKET_NAME: uploads
        USE_MINIO: "1"
        MINIO_ROOT_USER: admin
        MINIO_ROOT_PASSWORD: "{{ .minio_pass }}"
        AWS_ACCESS_KEY_ID: admin
        AWS_SECRET_ACCESS_KEY: "{{ .minio_pass }}"
        AWS_S3_ENDPOINT_URL: "http://plane-minio:9000"
  data:
    - secretKey: minio_pass
      remoteRef:
        key: plane-minio-password
        property: password
