apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: lidarr
  namespace: kube-system
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  endpoints:
  - dnsName: lidarr.kube.stevearnett.com
    recordType: CNAME
    targets:
    - kube.stevearnett.com
