apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - network-policy.yaml
  - namespace.yaml
  - jellyfin-helmrepository.yaml
  - jellyfin-helmrelease.yaml
  - seerr.yaml
  - prowlarr.yaml
  - radarr.yaml
  - sonarr.yaml
  - flaresolverr.yaml
  - lidarr.yaml
  - ingressroute-jellyfin.yaml
  - ingressroute-lidarr.yaml
  - ingressroute-seerr.yaml
  - ingressroute-prowlarr.yaml
  - ingressroute-radarr.yaml
  - ingressroute-sonarr.yaml
  - jellyfin-cache-pvc.yaml
  - external-secrets.yaml
