apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secret
  data:
    - secretKey: client-id
      remoteRef:
        key: oauth2-proxy-client-id
        property: password
    - secretKey: client-secret
      remoteRef:
        key: oauth2-proxy-client-secret
        property: password
    - secretKey: cookie-secret
      remoteRef:
        key: oauth2-proxy-cookie-secret
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-emails
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-emails
  data:
    - secretKey: .env.authenticated-emails
      remoteRef:
        key: oauth2-proxy-authenticated-emails
        property: password
