apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns/external-dns
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: kube-system
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
    provider: cloudflare
    cloudflare:
      apiToken:
        secretName: cloudflare-api-creds-root
        secretKey: CLOUDFLARE_API_TOKEN
    domainFilters:
      - stevearnett.com
    txtOwnerId: home-cluster
    logLevel: debug
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-creds-root
            key: CLOUDFLARE_API_TOKEN
    extraArgs:
      - --source=crd
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --source=ingress
    rbac:
      additionalPermissions:
        - apiGroups:
            - "externaldns.k8s.io"
          resources:
            - "dnsendpoints"
          verbs:
            - "get"
            - "watch"
            - "list"
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7979"
        prometheus.io/path: "/metrics"
