repositories:
  - name: emberstack
    url: https://emberstack.github.io/helm-charts
  - name: oauth2-proxy
    url: https://oauth2-proxy.github.io/manifests
  - name: stakater
    url: https://stakater.github.io/stakater-charts
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: plexinc
    url: https://plexinc.github.io/pms-docker/
  - name: csi-driver-smb
    url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  - name: caddy
    url: https://caddyserver.github.io/ingress
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: renovate
    url: https://docs.renovatebot.com/helm-charts
  - name: traefik
    url: https://traefik.github.io/charts
  - name: jellyfin
    url: https://jellyfin.github.io/jellyfin-helm
---
helmDefaults:
  historyMax: 3
---
environments:
  default:
---
templates:
---
releases:
  - name: reflector
    namespace: clustersecret
    chart: emberstack/reflector
    version: 9.0.322
    values:
      - updateOnChange: true
  - name: reloader
    namespace: kube-system
    chart: stakater/reloader
    version: 1.0.72
  - name: oauth2-proxy
    namespace: auth
    chart: oauth2-proxy/oauth2-proxy
    version: 9.0.0
    values:
      - config:
          existingSecret: oauth2-proxy-secret
        extraArgs:
          provider: google
          authenticated-emails-file: "/etc/oauth2-proxy/.env.authenticated-emails"
          upstream: "http://kubernetes-dashboard.kube-system.svc.cluster.local:80"
          cookie-secure: "true"
          redirect-url: "https://dashboard.kube.stevearnett.com/oauth2/callback"
          http-address: "0.0.0.0:4180"
          whitelist-domain: ".stevearnett.com"
          cookie-domain: ".stevearnett.com"
          skip-provider-button: "true"
        extraVolumes:
          - name: authenticated-emails
            secret:
              secretName: oauth2-proxy-emails
        extraVolumeMounts:
          - name: authenticated-emails
            mountPath: /etc/oauth2-proxy
            readOnly: true
        containerPorts:
          http: 4180
        service:
          portNumber: 4180
          type: ClusterIP
          ports:
            - name: proxy
              port: 4180
              targetPort: 4180
            - name: metrics
              port: 44180
              targetPort: 44180
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "44180"
            prometheus.io/path: "/metrics"
        ingress:
          enabled: false
  - name: oauth2-proxy-quotes
    namespace: quotes
    chart: oauth2-proxy/oauth2-proxy
    version: 9.0.0
    values:
      - config:
          existingSecret: oauth2-proxy-secret
        extraArgs:
          provider: google
          authenticated-emails-file: "/etc/oauth2-proxy/.env.authenticated-emails"
          upstream: "http://quotes-app.quotes.svc.cluster.local:8000"
          cookie-secure: "true"
          redirect-url: "https://quotes.stevearnett.com/oauth2/callback"
          http-address: "0.0.0.0:4180"
          whitelist-domain: ".stevearnett.com"
          cookie-domain: ".stevearnett.com"
          skip-provider-button: "true"
        extraVolumes:
          - name: authenticated-emails
            secret:
              secretName: oauth2-proxy-emails
        extraVolumeMounts:
          - name: authenticated-emails
            mountPath: /etc/oauth2-proxy
            readOnly: true
        containerPorts:
          http: 4180
        service:
          portNumber: 4180
          type: ClusterIP
          ports:
            - name: proxy
              port: 4180
              targetPort: 4180
            - name: metrics
              port: 44180
              targetPort: 44180
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "44180"
            prometheus.io/path: "/metrics"
        ingress:
          enabled: false
  - name: external-dns
    namespace: kube-system
    chart: external-dns/external-dns
    version: 1.14.5
    values:
      - provider: cloudflare
        cloudflare:
          apiToken:
            secretName: cloudflare-api-creds-root
            secretKey: CLOUDFLARE_API_TOKEN
        domainFilters:
          - stevearnett.com
        txtOwnerId: home-cluster
        logLevel: debug
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-creds-root
                key: CLOUDFLARE_API_TOKEN
        extraArgs:
          - --source=crd
          - --source=ingress
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "7979"
            prometheus.io/path: "/metrics"
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 55.5.0
    values:
      - crds:
          enabled: true
        prometheus:
          serviceMonitorSelectorNilUsesHelmValues: false
        grafana:
          enabled: true
          adminPassword: "admin"
        alertmanager:
          enabled: true
  - name: csi-driver-smb
    namespace: kube-system
    chart: csi-driver-smb/csi-driver-smb
  - name: plex
    namespace: plex
    chart: plexinc/plex-media-server
    version: "1.2.0"
    values:
      - service:
          type: ClusterIP
        ingress:
          enabled: false
        persistence:
          config:
            enabled: true
            size: 10Gi
          data:
            enabled: true
            size: 100Gi
        extraVolumes:
          - name: media-tv
            hostPath:
              path: /mnt/nas/tv
              type: Directory
          - name: media-movies
            hostPath:
              path: /mnt/nas/movies
              type: Directory
          - name: media-music
            hostPath:
              path: /mnt/nas/music
              type: Directory
        extraVolumeMounts:
          - name: media-tv
            mountPath: /media/tv
          - name: media-movies
            mountPath: /media/movies
          - name: media-music
            mountPath: /media/music
        claimSecret:
          name: plex-claim-secret
          key: PLEX_CLAIM
  - name: renovate
    namespace: renovate
    chart: renovate/renovate
    version: 39.142.0
    values:
      - cronjob:
          schedule: "0 * * * *"  # Run every hour
        renovate:
          config: |
            {
              "platform": "github",
              "repositories": ["kg6zjl/clusters"],
              "baseBranches": ["main"],
              "onboarding": false,
              "requireConfig": "optional",
              "enabledManagers": ["helmfile", "kubernetes", "helm-values"],
              "helmfile": {
                "fileMatch": ["helmfile\\.yaml$"]
              }
            }
        existingSecret: renovate-github-token
        env:
          - name: LOG_LEVEL
            value: "info"
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 33.2.0
    values:
      - ports:
          web:
            port: 8000
            exposedPort: 80
          websecure:
            port: 8443
            exposedPort: 443
        service:
          type: ClusterIP
          externalIPs:
            - 192.168.1.96
        ingressRoute:
          dashboard:
            enabled: true
        logs:
          general:
            level: INFO
          access:
            enabled: true
        providers:
          kubernetesIngress:
            enabled: true
            publishedService:
              enabled: true
  - name: jellyfin
    namespace: media
    chart: jellyfin/jellyfin
    version: 2.6.0
    values:
      - service:
          type: ClusterIP
          port: 8096
        ingress:
          enabled: false
        persistence:
          config:
            enabled: true
            size: 10Gi
          cache:
            enabled: true
            size: 5Gi
          media:
            enabled: true
            type: hostPath
            hostPath: /mnt/nas
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
