apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - flux-system/syncs
  - traefik
  - cert-manager
  # - oauth2-proxy (managed by Flux)
  - cluster-secrets
  - monitoring
  - home-assistant
  - ai-services
  - gpu-operator
  - plex
  - media
  - vpn
  # - cloudflared (managed by Flux)
  # - speedtest (managed by Flux)
  # - local-services (managed by Flux)
  # - registry (managed by Flux)
  # - netalertx
  # - quotes (managed by Flux)
  # - headlamp (managed by Flux)
  # - frigate (managed by Flux)
  # - mqtt (managed by Flux)
  # - meshtastic (managed by Flux)
  # - meshtastic-bot (managed by Flux)
  # - pihole (managed by Flux)
  # - openclaw (managed by Flux)
  - kube-system/coredns-configmap-patch.yaml
  - kube-system/dnsendpoint-openclaw.yaml
  - renovate
  - github-runners
