apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - flux-system/syncs
  - traefik
  - cert-manager
  - oauth2-proxy
  - cluster-secrets
  - monitoring
  - home-assistant
  - ai-services
  - gpu-operator
  - plex
  - media
  - vpn
  - cloudflared
  - speedtest
  - local-services
  - registry
  # - netalertx
  # - quotes
  - headlamp
  - frigate
  - mqtt
  - meshtastic
  - meshtastic-bot
  - pihole
  - kube-system/coredns-configmap-patch.yaml
  - kube-system/dnsendpoint-openclaw.yaml
  - renovate
  - github-runners
  - openclaw
