apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik
  - cert-manager
  - oauth2-proxy
  - cluster-secrets
  - dashboard
  - monitoring
  - home-assistant
  - ai-services
  - gpu-operator
  - plex
  - media
  - vpn
  - cloudflared
  - speedtest
  - local-services
  - registry
  # - netalertx
  # - quotes
  - headlamp
  - frigate
  - meshtastic
  - pihole
  - kube-system/coredns-configmap-patch.yaml
  - renovate
