version: "3"
tasks:
  default:
    desc: "You are here"
    cmds:
      - task --list-all

  apply:
    cmds:
      - helm repo update
      - export $(grep -v '^#' .env | xargs) && helmfile sync
      - kubectl apply -k .
