apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runner-autoscaler
  namespace: github-runners
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    name: github-runner
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - clusters
