apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - rbac.yaml
  - runner-deployment.yaml
  - external-secrets-namespace.yaml
  - external-secrets-store.yaml
  - external-secrets.yaml
  - network-policy.yaml
