apiVersion: v1
kind: ServiceAccount
metadata:
  name: onepassword
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onepassword-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: onepassword-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onepassword-reader
subjects:
  - kind: ServiceAccount
    name: onepassword
    namespace: external-secrets
