apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner
  namespace: github-runners
spec:
  replicas: 2
  template:
    spec:
      repository: kg6zjl/clusters
      labels:
        - self-hosted
        - kubernetes
      image: registry.kube.stevearnett.com/github-runner-optimized:latest
      env:
        - name: REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-auth
              key: REGISTRY_PASSWORD
        - name: REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: registry-auth
              key: REGISTRY_USERNAME
