apiVersion: v1
kind: ConfigMap
metadata:
  name: headlamp-kubeconfig
  namespace: headlamp
data:
  config: |
    apiVersion: v1
    kind: Config
    current-context: in-cluster
    clusters:
    - name: in-cluster
      cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes.default.svc
    contexts:
    - name: in-cluster
      context:
        cluster: in-cluster
        user: in-cluster
        namespace: default
    users:
    - name: in-cluster
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token