apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - thinkcentre01
                      - thinkcentre02
                      - kube-nuc
      initContainers:
      - name: copy-config
        image: ghcr.io/blakeblackshear/frigate:stable
        command:
        - sh
        - -c
        - |
          cp /config-src/config.yaml /config-dest/config.yaml
          chmod 666 /config-dest/config.yaml
        volumeMounts:
        - name: config
          mountPath: /config-dest
        - name: config-src
          mountPath: /config-src
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:stable
          envFrom:
            - secretRef:
                name: frigate-credentials
            - secretRef:
                name: frigate-secrets
          env:
            - name: LIBVA_DRIVER_NAME
              value: "radeonsi"
            - name: TZ
              value: "America/Los_Angeles"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media/frigate
            - name: cache
              mountPath: /tmp/cache
            - name: dri
              mountPath: /dev/dri
            - name: shm
              mountPath: /dev/shm
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 8554
              name: rtsp
      volumes:
        - name: config
          emptyDir: {}
        - name: config-src
          configMap:
            name: frigate-config
        - name: media
          persistentVolumeClaim:
            claimName: frigate-media-pvc
        - name: cache
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: dri
          hostPath:
            path: /dev/dri
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
