apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: frigate-secrets
  data:
    - secretKey: FRIGATE_RTSP_PASSWORD
      remoteRef:
        key: frigate-rtsp-password
        property: password
    - secretKey: FRIGATE_RTSP_USERNAME
      remoteRef:
        key: frigate-rtsp-username
        property: password
