apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - gotk-components.yaml
  - arc-helmrepository.yaml
  - traefik-helmrepository.yaml
  - prometheus-community-helmrepository.yaml
  - grafana-helmrepository.yaml
  - actions-runner-controller-helmrepository.yaml
  - syncs-kustomization.yaml
