apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 1h
  chart:
    spec:
      chart: spegel
      sourceRef:
        kind: HelmRepository
        name: spegel
        namespace: flux-system
      version: 0.6.0
  values:
    spegel:
      containerdSock: /var/snap/microk8s/common/run/containerd.sock
      containerdRegistryConfigPath: /var/snap/microk8s/current/args/certs.d
      containerdContentPath: /var/snap/microk8s/common/var/lib/containerd/io.containerd.content.v1.content
      containerdMirrorAdd: true
      mirroredRegistries:
        - https://docker.io
        - https://ghcr.io
        - https://quay.io
      additionalMirrorTargets:
        - https://registry.kube.stevearnett.com
