apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: logging
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./home-cluster/logging
  prune: true
  sourceRef:
    kind: GitRepository
    name: clusters
  targetNamespace: logging
  timeout: 2m0s
