apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: speedtest
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./home-cluster/speedtest
  prune: true
  sourceRef:
    kind: GitRepository
    name: clusters
  targetNamespace: speedtest
  timeout: 2m0s
