apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./home-cluster/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: clusters
  targetNamespace: traefik
  timeout: 2m0s
