apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - longhorn-helmrepository.yaml
  - longhorn-helmrelease.yaml
  - network-policy-metrics.yaml
  - externalsecret-longhorn-ui-auth.yaml
  - middleware-longhorn-ui.yaml
  - ingressroute-longhorn-ui.yaml
  - network-policy-ui.yaml
