apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: cert-manager-secrets
  data:
    - secretKey: username
      remoteRef:
        key: certbot-username
        property: password
    - secretKey: password
      remoteRef:
        key: certbot-password
        property: password
    - secretKey: CERT_MANAGER_EMAIL
      remoteRef:
        key: certbot-email
        property: password
