apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

secretGenerator:
- name: nas-smb-credentials
  options:
    disableNameSuffixHash: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "backup"

resources:
  - external-secrets.yaml
  - clusterissuer.yaml
  - certificate.yaml
  - sync-cert-cronjob.yaml
  - sync-cert-namespaces-cronjob.yaml
  - servicemonitor.yaml

patches:
  - target:
      group: ""
      version: v1
      kind: Service
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9402"
          prometheus.io/path: "/metrics"
