apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: flux-operator
spec:
  endpoints:
    - dnsName: flux.kube.stevearnett.com
      recordType: CNAME
      targets:
        - kube.stevearnett.com
