apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meshtastic-bot-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: meshtastic-bot-secrets
  data:
    - secretKey: MESHMONITOR_TOKEN
      remoteRef:
        key: meshtastic-bot-secrets
        property: password
    - secretKey: BOT_NODE_NUM
      remoteRef:
        key: meshtastic-bot-secrets
        property: BOT_NODE_NUM
    - secretKey: BOT_ALIAS
      remoteRef:
        key: meshtastic-bot-secrets
        property: BOT_ALIAS
