apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: meshtastic

resources:
  - namespace.yaml
  - deployment.yaml

secretGenerator:
  - name: meshtastic-bot-config
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
