apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - dex-helmrepository.yaml
  - dex-helmrelease.yaml
  - dex-external-secrets.yaml
  - ingressroute.yaml
  - dnsendpoint.yaml
  - networkpolicy.yaml
