apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-ro-creds
  namespace: unifi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: unifi-ro-creds
  data:
  - secretKey: username
    remoteRef:
      key: unifi-hermes-ro-creds
      property: username
  - secretKey: password
    remoteRef:
      key: unifi-hermes-ro-creds
      property: password
