apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - network-policy.yaml
  - unpoller-deployment.yaml
  - unpoller-service.yaml
  - unpoller-servicemonitor.yaml
  - unifi-route-audit-20260929.yaml
