apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: expressvpn-ovpn
spec:
  refreshInterval: 168h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: expressvpn-ovpn
    creationPolicy: Owner
  data:
    - secretKey: filename
      remoteRef:
        key: express-vpn-auth
        property: filename
    - secretKey: ovpn_text
      remoteRef:
        key: express-vpn-auth
        property: ovpn_text
