apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: vpn-secret
  data:
    - secretKey: username
      remoteRef:
        key: vpn-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: vpn-credentials
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: qbittorrent-secret
  data:
    - secretKey: QBITTORRENT__AUTH__ADMIN_PASSWORD_HASH
      remoteRef:
        key: vpn-credentials
        property: password
