apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: expressvpn-ovpn
spec:
  refreshInterval: 168h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: expressvpn-ovpn
    creationPolicy: Owner
  data:
    - secretKey: expressvpn.ovpn
      remoteRef:
        key: express-vpn-auth
        property: expressvpn.ovpn
