apiVersion: v1
kind: Namespace
metadata:
  name: vpn
---
apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: vpn
spec:
  selector:
    app: gluetun
  ports:
  - port: 8080
    targetPort: 8080
    name: qbittorrent
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: vpn
  labels:
    app: gluetun
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
      initContainers:
      - name: init-config
        image: busybox:1.36
        securityContext:
          privileged: true
        command: ['sh', '-c', 'mkdir -p /config/qBittorrent'] # && cp /config-init/qBittorrent.conf /config/qBittorrent/qBittorrent.conf || true']
        volumeMounts:
        - name: config
          mountPath: /config
        - name: config-init
          mountPath: /config-init

      containers:
      - name: gluetun
        image: qmcgaw/gluetun:v3.40.3
        securityContext:
          privileged: true
          capabilities:
            add: [NET_ADMIN, SYS_MODULE]
        env:
        - name: VPN_SERVICE_PROVIDER
          value: expressvpn
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: vpn-secret
              key: username
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vpn-secret
              key: password
        - name: SERVER_COUNTRIES
          value: "USA"
        - name: TZ
          value: America/New_York
        - name: FIREWALL
          value: "on"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fd00::/8,1.1.1.1/32,1.0.0.1/32"
        - name: FIREWALL_INPUT_PORTS
          value: "8080"
        - name: FIREWALL_VPN_ENDPOINT_IP
          value: "1"
        - name: HEALTH_CHECK_PERIOD
          value: "0"
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: downloads
          mountPath: /downloads
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: America/New_York
        - name: WEBUI_PORT
          value: "8080"
        - name: WEBUI_ADDRESS
          value: "0.0.0.0"
        - name: QBITTORRENT__AUTH__ADMIN_PASSWORD_HASH
          valueFrom:
            secretKeyRef:
              name: qbittorrent-secret
              key: QBITTORRENT__AUTH__ADMIN_PASSWORD_HASH
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config-init
        configMap:
          name: qbittorrent-config
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
      - name: downloads
        hostPath:
          path: /mnt/nas/torrents/Downloads
          type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: vpn
data:
  qBittorrent.conf: |
    [Preferences]
    WebUI\Address=*
    WebUI\Port=8080
    WebUI\Username=admin123
    [BitTorrent]
    Session\DefaultSavePath=/downloads
    Session\TempPath=/downloads/temp
    Session\TempPathEnabled=true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: vpn
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
