---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stevearnett-com-tls
  namespace: infra
spec:
  secretName: stevearnett-com-tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: stevearnett.com
  dnsNames:
  - stevearnett.com
  - www.stevearnett.com
  - "*.stevearnett.com"
