apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: pihole-secrets
  data:
    - secretKey: PIHOLE_WEB_PASSWORD
      remoteRef:
        key: pihole-web-password
        property: password
