apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quotes-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: quotes-secrets
  data:
    - secretKey: registry_username
      remoteRef:
        key: quotes-registry-creds
        property: username
    - secretKey: registry_password
      remoteRef:
        key: quotes-registry-creds
        property: password
