apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quotes-registry-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: quotes-registry-auth
    creationPolicy: Owner
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: quotes-registry-creds
        property: dockerconfigjson
