apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quotes-registry-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: quotes-registry-auth
    creationPolicy: Owner
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: quotes-registry-creds
        property: dockerconfigjson
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secret
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: quotes-oauth2-proxy
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: quotes-oauth2-proxy
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: quotes-oauth2-proxy
        property: cookie-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-emails
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-emails
    creationPolicy: Owner
  data:
    - secretKey: .authenticated-emails
      remoteRef:
        key: quotes-authenticated-emails
        property: emails
