apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quotes

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - pvc.yaml
  - external-secrets.yaml

secretGenerator:
  - name: quotes-registry-auth
    type: kubernetes.io/dockerconfigjson
    literals:
      - .dockerconfigjson={"auths":{"registry.kube.stevearnett.com":{"username":"$(REGISTRY_USERNAME)","password":"$(REGISTRY_PASSWORD)"}}}

generatorOptions:
  disableNameSuffixHash: true
