apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meshtastic-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: meshtastic-secrets
  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: meshtastic-admin
        property: password
    - secretKey: MQTT_USERNAME
      remoteRef:
        key: mqtt-credentials
        property: username
    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: mqtt-credentials
        property: password
