apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - network-policy.yaml
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - ingressroute-tcp.yaml
  - dnsendpoint.yaml
  - external-secrets.yaml
  - backup-external-secret.yaml
  - backup-cronjob.yaml
  - backup-network-policy.yaml

configMapGenerator:
  - name: meshmonitor-scripts
    files:
      - scripts/banana.py
      - scripts/test_gauge.py

generatorOptions:
  disableNameSuffixHash: true
