name: Renovate Artifact Helper

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  update-helmfile-artifacts:
    name: Update Helmfile Lock & Artifacts
    if: github.actor == 'renovate[bot]' || contains(github.head_ref, 'renovate/')
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
    env:
      PATH: /opt/tools/bin:/opt/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PYTHONPATH: /opt/tools/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helmfile Deps & Lock
        run: |
          cd home-cluster
          helmfile deps

      - name: Commit Updated Artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update helmfile artifacts"
          file_pattern: 'home-cluster/helmfile.lock'
